import { fontRoles } from '../fonts';
import type { PosterTemplate } from '../types';
import { renderGingham } from './gingham-layout';

export const ginghamTemplate: PosterTemplate = {
  id: 'gingham',
  name: '田园格纹',
  description: '野餐桌布 · 标签卡',
  recommendedItems: '1–8 件',
  typography: {
    display: fontRoles.serif,
    title: fontRoles.sans,
    body: fontRoles.sans,
    numeric: fontRoles.sans,
    handwriting: fontRoles.handwriting,
  },
  previewFonts: ['chineseHandwriting', 'handwriting', 'serif', 'sans'],
  exportFonts: ['chineseHandwriting', 'handwriting', 'serif', 'sans'],
  palettes: [
    {
      id: 'sage',
      label: '蓝绿格纹',
      background: '#f0f1e5',
      surface: '#fffbed',
      primary: '#7d8c70',
      secondary: '#9ebbbe',
      text: '#46473a',
      muted: '#918976',
      price: '#99635d',
    },
    {
      id: 'pink',
      label: '草莓粉',
      background: '#f1dce2',
      surface: '#fffaf2',
      primary: '#ad7182',
      secondary: '#ddb0bd',
      text: '#49383d',
      muted: '#8d747b',
      price: '#a94f65',
    },
    {
      id: 'blue',
      label: '晴空蓝',
      background: '#dce9ed',
      surface: '#fffaf0',
      primary: '#5e7f8a',
      secondary: '#a8c6cf',
      text: '#304047',
      muted: '#708188',
      price: '#a35f58',
    },
    {
      id: 'yellow',
      label: '柠檬黄',
      background: '#f1e7bd',
      surface: '#fffaf1',
      primary: '#97833f',
      secondary: '#d8c979',
      text: '#453f2d',
      muted: '#847b5f',
      price: '#ad6452',
    },
  ],
  defaultOptions: {
    palette: 'sage',
    density: 'BALANCED',
    priceStyle: 'PRICE_PROMINENT',
    showNote: true,
  },
  render: renderGingham,
};
