import { fontRoles } from '../fonts';
import type { PosterTemplate } from '../types';
import { renderInvitation } from './invitation-layout';

export const invitationTemplate: PosterTemplate = {
  id: 'invitation',
  name: '婚礼请柬',
  description: '花束缎带 · 双拱请柬',
  recommendedItems: '1–6 件',
  typography: {
    display: fontRoles.serif,
    title: fontRoles.serif,
    body: fontRoles.sans,
    numeric: fontRoles.serif,
    handwriting: fontRoles.serif,
  },
  exportFonts: ['serif', 'chineseSerif', 'handwriting'],
  palettes: [
    {
      id: 'champagne',
      label: '香槟',
      background: '#f7f1e6',
      surface: '#fffaf1',
      primary: '#9b7b55',
      secondary: '#d8c3a8',
      text: '#40372d',
      muted: '#8c7d6e',
      price: '#8d5d45',
    },
    {
      id: 'blush',
      label: '雾粉',
      background: '#f5e9e9',
      surface: '#fffafa',
      primary: '#a87378',
      secondary: '#dfbec1',
      text: '#49383a',
      muted: '#8f7377',
      price: '#96525e',
    },
    {
      id: 'sage',
      label: '鼠尾草',
      background: '#edf0e8',
      surface: '#fffdf6',
      primary: '#728064',
      secondary: '#c4ceba',
      text: '#354031',
      muted: '#74806d',
      price: '#6c5847',
    },
    {
      id: 'mist-blue',
      label: '雾蓝',
      background: '#e9eff2',
      surface: '#fbfdfd',
      primary: '#617986',
      secondary: '#bacbd3',
      text: '#334148',
      muted: '#71838b',
      price: '#775f65',
    },
  ],
  defaultOptions: {
    palette: 'champagne',
    density: 'BALANCED',
    priceStyle: 'PRICE_PROMINENT',
    showNote: true,
  },
  render: renderInvitation,
};
